#!/usr/bin/bash

#start swwww
swww-daemon
swww query || swww init

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#show the correct wallpapper based on the theme
if [ $THEMEIS == "dark.css" ]; then
   # swww img ~/.config/hypr/wallpaper-dark.jpg
     swww img ~/Wallpapers/4k-blue-background.jpg --outputs HDMI-A-1
	 swww img ~/Wallpapers/wp5076799-anime-alone-romantic-dark-wallpapers.jpg --outputs DP-2
	 swww img ~/Wallpapers/wp5475508-anime-scenery-4k-wallpapers.jpg --outputs DP-1
else
    swww img ~/.config/hypr/wallpaper.jpg
fi
